### PR TITLE
Modification: UI, Advanced Controls

### PR DESCRIPTION
**Pull request by sabyasachi-basu-i**
modified UI in Login; added Advanced Control Selection; Scope for Improvement: Mobile Responsiveness

Worked on **Issue #243** Suggestion: Config options to configure the main page -> New UI takes care of controls

UI1
UI2
UI3

### CODE REVIEW

**Comment by cedrozor** [comment]
Wow many thanks! indeed, Myrtille needs a UI rework, as I confessed into a recent [Myrtille blog](https://www.freerdp.com/2020/11/09/hi-myrtille) on the FreeRDP website, so it's a perfect timing :)

Did you added FreeRDP as a git submodule ? from commit 90d1526a7d3d7c8b67aeaeda10f711928fb4f045:

> Myrtille.RDP/FreeRDP
> Submodule FreeRDP added at 8caf23 
> 

I prefer to keep Myrtille and FreeRDP separated. Submodules are linked to particular commits into the root repo and I find it tricky to manage. I have tags into the Myrtille's FreeRDP fork (https://github.com/cedrozor/FreeRDP/tags) so that it's possible to checkout the FreeRDP branch which corresponds to a specific Myrtille version.

Apart from this detail, the rest looks nice!

**Comment by sabyasachi-basu-i** [comment]
No. I followed the same approach as you. I did not add Git submodules of FreeRDP. It needs to be added as a different clone/pull.

Also, I found a few small bugs. I missed the Admin page UI. also, due to modification in the login css, the ```hostConnectDiv``` is keeping a fixed ```view height``` blank space in the page. will work on the same. I'll keep my commit updated.

Also, I have a few architectural questions. I was planning to get rid of the FreeRDP altogether (eliminating the necessity of the older ```.c``` headers; which will help in lesser unmanaged resources and memory leaks. Maybe something similar to AxMSTSCLib(not sure if it'll work). Because, I was able to load test the solution with `32 parallel session` from a beefy `Windows Server 2019(with RDS module) - 80 GB(RAM) 20 vCPU 25600 IOPS`.

Everyone was connected, but the rendering went remarkable slow, leading the session to almost unusable(some people were still using it with very delayed speed. (note: I had a 1hr flush interval in IIS. to flush the memory). Hence, the above thought.

**Comment by cedrozor** [comment]
Strange this submodule commit message then, I will check that.

In your latest commit, you changed the FreeRDP default settings:
`FreeRDPWallpaper = true`

The wallpaper is a degrading factor for display rendering performance. In the same way as the connection settings, I think Myrtille could benefit from a UI for the display settings (and, by extension, the FreeRDP settings). The default FreeRDP params could stay in `Myrtille.Services.exe.config` but be overriden by the user (from a UI).

You also changed "Myrtille" as product name by "InnoRemote" into `Myrtille.Setup.vdproj` and had yourself and your fork of Myrtille as author and url. Of course, if I merge this pull request into the base repo, I will have to change this.

Your pull request is a quite large. I will have to take some time to undertand all of it and possibly adapt it (for example, `WebForm1.aspx` is not an explicit name), in order to keep control on it and avoid any side effects.

Thanks again! :)

**Comment by sabyasachi-basu-i** [comment]
I am sorry! I kept a few testing change and forgot to change them later. Wait one more day. I'll commit a cleaner section. I'll change the InnoRemote stuff too. Thank you for the review, Sorry for the mistakes again!

**Comment by sabyasachi-basu-i** [comment]
Dear @cedrozor 
I modified the earlier comments(removing my test files and modifications); also, added advanced control in config. and, you don't really have to keep my name in the styles etc. I am able to contribute to this fantastic project is itself an achievement. Hope to contribute more in future. Send me the ideas you have, I'll see what I can do. Also, did you get a chance to look at the library I mentioned earlier? Please let me know your thoughts(if possible).

**Comment by cedrozor** [comment]
> Also, I have a few architectural questions. I was planning to get rid of the FreeRDP altogether (eliminating the necessity of the older .c headers; which will help in lesser unmanaged resources and memory leaks. Maybe something similar to AxMSTSCLib(not sure if it'll work). Because, I was able to load test the solution with 32 parallel session from a beefy Windows Server 2019(with RDS module) - 80 GB(RAM) 20 vCPU 25600 IOPS.
> 

I'm not sure to understand what you want to do. By replacing FreeRDP by the mstsc ActiveX component, you don't have control over the code and hence can't generate display updates, as I do into https://github.com/cedrozor/FreeRDP/blob/master/client/Windows/wf_myrtille.cpp

> Everyone was connected, but the rendering went remarkable slow, leading the session to almost unusable(some people were still using it with very delayed speed. (note: I had a 1hr flush interval in IIS. to flush the memory). Hence, the above thought.

I don't understand either the IIS memory flush you are speaking about (recycling the application pool?).

>   (commit or discard the untracked or modified content in submodules)
>         modified:   Myrtille.RDP/FreeRDP (untracked content)
> 

The git commands don't show the moment you added FreeRDP as submodule, but it must have been prior this.

**Comment by sabyasachi-basu-i** [comment]
> I'm not sure to understand what you want to achieve. By replacing FreeRDP by the mstsc ActiveX component, you don't have control over the code and hence can't generate display updates, as I do into https://github.com/cedrozor/FreeRDP/blob/master/client/Windows/wf_myrtille.cpp

ok. I need to study more about this. :)

> In which context did you loaded 32 concurrent sessions?
in a Win Server 2019. I started 32 parallel user session. I had RDS module installed.

> I don't understand either the IIS memory flush you are speaking about (recycling the application pool?).
Yes. That's correct. Reclying.

> The git commands don't show the moment you added FreeRDP as submodule, but it must have been prior this.
I'll probably create another clone.

**Comment by sabyasachi-basu-i** [comment]
Hi @cedrozor ,
file download now works for dynamic folder GUID, configurable from Web.config; 

img1
img2


Scope 1: will keep an Input possibly for user too to provide file path and that'll generate custom *guid* to get the files from remote machine (Where they have access)

Scope 2: Need to work on the GUI(popup style) for the file sharing (it's a pop-up. hence a separate window) it'll be interesting to modify. and, potentially prone to lesser error in the ID conflicts with predefined classes. 

Scope 3: Right now it does not work for custom GUID (like any folder from Computer or network path). I need to study more to make that happen. [Resulted in below error]
err1

**Comment by sabyasachi-basu-i** [comment]
Question: is Issue #232 something similar to what I am also trying to achieve?

**Comment by Neustradamus** [comment]
@sabyasachi-basu-i, @saby-iw: Why have you closed your PR?

**Pull request closed without merging**
