### PR TITLE
MFA and Enterprise Mode

### PR DESCRIPTION
**Pull request by bigpjo**
Addition of One Time Passcode authentication using 3rd party service.

Added enterprise mode to allow pre authentication against a domain and host creation etc to behave like RDP gateway i.e. list of hosts users is allowed to access based on AD group membership.

New method to create session URL's, stores credentials server side and expires after a single use.

### CODE REVIEW

**Comment by cedrozor** [comment]
Hi Paul,

I'm back from long vacations, I will put some time on it for integration ;)

**Comment by bigpjo** [comment]
Hi Cedric

How are you? I hope you are well and had a nice vacation.

I have been working on changes to our 2FA platform to include geolocation
policies to restrict authentication based on location, trying to bring
functionality level with other service providers i.e. duo.

There will be publishing a new version of the oasis.integration.dll
available on github and nuget later today.

I have been using Myrtille quite a lot where I implemented it with the
enterprise functions and 2fa and the company is extremely happy with it,
slight issue with cursors using office 2010 products but thats a freerdp
issue i believe.

May I ask, do you think there is merit in SMS passcodes and push
notifications? I have been asked to include them but the group can not make
a decisive decision so I thought I would ask your opionion?


Regards

Paul

**Comment by cedrozor** [comment]
Hi Paul,

Indeed, geolocation is a nice addition :) if you feel that a new PR would be convenient (this one already has some conflicts), please go on.

SMS passcodes and notifications, why not but it adds some complexity (phone numbers management). For a start, I think that 2FA is nice enough.

FreeRDP 2.0 is brand new; it brings many new features and improvement but also have some troubles (for example, authentication sometimes fail when using the [hostname instead of IP](https://github.com/FreeRDP/FreeRDP/issues/4351))... I will look into it. What problem exactly regarding mouse cursors? did you try to [enable/disable the cursor shadow](http://www.thewindowsclub.com/enable-disable-mouse-pointer-shadow-windows)? (FreeRDP had some troubles with that in the past).

**Comment by bigpjo** [comment]
Hi Cedric

I have commited additional changes which have been included in my pull
request.

The commit now passes the client ip to the MFA adapter to allow the OASIS
platform to enforce access control policies based on location and
connection type (i.e. restrict anonymous vpn and tor exit nodes).

With regards the cursor issue I mentioned, this only seems to apply when
using Office 2010 products, for instance if you start a new email, the
message text area does not show the cursor therefore you do not know where
you are when typing.

Regards

Paul

**Comment by cedrozor** [comment]
Thanks Paul, I prioritized blocking issues with FreeRDP 2.0 RC is my last commits, but I'll definitelly have a look now! :)

About that, if you could connect to your servers using FQDN, ipv6 or netbios name, instead of ipv4, and tell me if all is ok? don't hesitate to add some connection broker(s), just for fun :p

**Comment by bigpjo** [comment]
Hi Cedric

I have tried fqdb and NetBIOS name with the same result. Can not tests ipv6
as it is not enabled on our customers machines

I will see if I can get office 2010 and try it on our machines.

If my pull request is merged I am going to tackle remote printing. I have
discussed with one of my developers potential solutions and we think we may
have it. So once I can schedule the work I will run the idea past you and
see what you think

**Comment by cedrozor** [comment]
Is the myrtille machine on the same domain as the target machines? its DNS (primary or secondary) should point to the domain controller IP for the FQDNs resolution to succeed.

**Comment by bigpjo** [comment]
Yes they are.

**Comment by cedrozor** [comment]
Do you have something useful in the myrtille/freerdp logs (to enable [there](https://github.com/cedrozor/myrtille/blob/master/Myrtille.Services/app.config#L93) and restart Myrtille.Services), or the windows/RDS event logs, either client (myrtille machine) and server (rdp server) sides?

There are some weird issues since FreeRDP 2.0 RC0, I may consider rolling back to a stable version :/

**Comment by bigpjo** [comment]
I was hoping that the new merge of reports 2.0 may resolve the issue. Are
there any changes you have made since 1.6.2 which would prevent direct drop
in of the new version for testing

**Comment by cedrozor** [comment]
I didn't saw any change in FreeRDP 2.0 regarding the [mouse cursor management](https://github.com/FreeRDP/FreeRDP/blob/master/client/Windows/wf_graphics.c#L192).

Myrtille 1.7.0 does prevent FreeRDP 2.0 to hang when using an FQDN for connection or broker redirection. So yes, you can use it for testing but I don't think it will fix the Office 2010 cursor.

I installed Word 2010 for a previous myrtille issue (which was finally related to the pipes communication). What do I need to replicate the cursor issue?

**Comment by bigpjo** [comment]
If you open word and click anywhere in the area where you would type it
does not show a cursor. I could take a screenshot but I would be a picture
of a blank word document with no cursor. If you type some text and then
click within the middle of a word you will not see the type cursor (or I
don't in testing) would you like me to send a screenshot?

**Comment by cedrozor** [comment]
What browser do you use? Does the problem occurs with every browser?

**Comment by bigpjo** [comment]
Tried Ie and chrome

**Comment by cedrozor** [comment]
For your tests, could you enable/disable the [mouse cursor shadow](http://www.thewindowsclub.com/enable-disable-mouse-pointer-shadow-windows)? Older versions of myrtille had a blue shadow under the cursor because of that feature

**Comment by bigpjo** [comment]
I can try.

Please could I confirm. I am not referring to the mouse pointer.

I am referring to the cursor whilst typing to indicate where the next type
position would be.

**Comment by cedrozor** [comment]
Ah my bad :/ then you could try something, because rdp may prevent the text cursor from blinking... but if starts hidden, it will stay hidden (lol).

Set the following registry key on the rdp server:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp\UserOverride\Control Panel\Desktop -> DisableCursorBlink=dword:00000001

Or just import the pre-configured file https://github.com/cedrozor/myrtille/blob/master/Myrtille.Setup/RDPSetup.reg

**Comment by bigpjo** [comment]
Thanks for the suggestion. I will try tomorrow if that's ok and confirm

**Comment by bigpjo** [comment]
Hi Cedric

I have tried the registry entry with no success. Does the server require a
reboot after changing?

**Comment by cedrozor** [comment]
Hi Paul,

Yes, I think so.

Cedric

**Comment by bigpjo** [comment]
Hi Cedric,

I have merged the 1.7.0 with the changes I made for OTP and Enterprise Mode if you would be happy to look at it now that would be great.

Thanks

**Comment by cedrozor** [comment]
Hi Paul,

I pulled the latest code from your fork and made some tests. It's working :) but I had some troubles and I'm afraid it will be difficult for the end user.

First at all, you should resync your fork, so I can test with all the latest features (missing the right-click button into the toolbar for example) and avoid conflicts in this PR and the forthcoming ones.

Then there is a major need for some help into the documentation.md file (a new section explaining the enrollment process on your MFA platform/dashboard, the configuration of the api key, app key, app id on myrtille, etc.). It's also not clear enough that the end user must install an OTP application on its smartphone and scan a QR code upon registration in order to be able to generate OTPs for myrtille.

The new home page is a bit confusing, with the user name that should match both the user name defined on the MFA platform and on the enterprise domain, while the password is the domain one. Also, the home page sometimes displays the original myrtille login form; a refresh does fix it.

The servers list page is nice but I had to figure out how to delete an host (clicking the text and not the image). I think a red cross or trash icon next to the host image would be more intuitive than a delete button into the edit host popup (but that's just a detail).

After a session disconnect, there is no redirect to the home page (the servers list is there but not clickable, only the logout button works).

Sorry for being picky but it's to anticipate a lot of frustration and relieve the issue tracker ;)

Thanks,
Cedric

**Comment by cedrozor** [comment]
Ah and a detail ;) I thought you wanted to open source your [nuget OTP adapter](https://www.nuget.org/packages/OASIS.Integration/)?

**Comment by bigpjo** [comment]
Hi Cedric

Thank you for feedback. I will try to do my best to answer.

1) Starting with the simple one ;), the nuget OTP adapter is open source,
or part of it, the oasis.integration component can be found at
https://github.com/OliveInnovations/OASIS it needs the latest release
synced but it is there.

2) The resync of the fork. Can you please confirm you have version 1.7.1
unless something has gone wrong the the version you should have tested
should be 1.7.0 merged with my changes, maybe today I will delete the pull
request and create another just to be sure. I am running it on my server
and the right click toggle is definitely there and working.

3) Login page, sometimes mrytille sometimes enterprise, when the page loads
it checks that the enterprise services/mfa are enabled before displaying
input boxes, if the myrtille.services is not running when the page is
loaded it will display the normal login page, shall I change to hide the
login page if the services are not running?

4) Password on login, the whole point behind the enterprise mode is that
there is preauthentication against a domain to verify what servers the user
is allowed to access, therefore if enterprise mode is enabled the password
must be the domain password.

5) MFA, the user must be enroled for MFA, the OASIS platform has a
directory sync service which will sync and send registration emails for all
users they wish to have MFA. If Myrtille is not used in enterprise mode,
the owner will have to register the user in the OASIS administration
platform to register for MFA, in both cases the user will have instructions
to download google authenticator.

6) The server delete, I totally understand, I can change the link to have
the word "edit" when an administrator is viewing to make it more intuitive.
I can also add a delete icon/button if you think that would be better!

7) Session disconnect redirect to login. I appreciate this could be found
as being frustrating, when a user preauthenticates the enterprise adapter
stores the user credentials and a session key encrypted in the database,
this is valid for no more than 1 hour, when a user connects to a server the
credentials are read from the database based on session key and then
deleted, this is to ensure that whist the user is using the service no
credentials are stored client side (at all!) and server side in any form
that can be used by someone who should not have access. Because of this,
upon disconnect the session no longer exists and the user needs to login
again. I have done some Q&A sessions in the 2 companies I have now
implemented Myrtille and in both cases this is the preferred option.

I think all in all enterprise mode may not be required by Myrtille users,
however I see the potential of Myrtille and its uses, as you are aware from
our previous discussions what is required in an enterprise environment may
not be the same as users who wish to access there home network. I tried to
abstract Myrtille from the enterprise functions to give the users the
choice.

With regards MFA and OASIS, yes it is a little complicated and feedback to
streamline the process is welcome, the issue is that to enable 2fa you need
to store keys for generation of the TOTP codes, it can be changed to
provide a services much the same as enterprise mode i.e. create databases,
handle enrollment of users etc but I dont think the whole process will be
much simpler than integration with OASIS. Again as with previous
discussions, OASIS is optional, it can be removed if the community and
yourself do not want it in there.

I look forward to hearing back from you.

Regards

Paul

**Comment by cedrozor** [comment]
Hi Cedric

Thank you for feedback. I will try to do my best to answer.

1) Starting with the simple one ;), the nuget OTP adapter is open source,
or part of it, the oasis.integration component can be found at
https://github.com/OliveInnovations/OASIS it needs the latest release
synced but it is there.

_Nice, perhaps you can indicates it here : https://www.nuget.org/packages/OASIS.Integration/ :)_

2) The resync of the fork. Can you please confirm you have version 1.7.1
unless something has gone wrong the the version you should have tested
should be 1.7.0 merged with my changes, maybe today I will delete the pull
request and create another just to be sure. I am running it on my server
and the right click toggle is definitely there and working.

_I think the auto-merge didn't worked well because this PR has some conflicts (see below). Default.aspx, which defines the right click toggle, is one of them. Perhaps, yes, better delete and make a new PR. By the way, resyncing a fork may not be easy, I myself followed some guidelines, to resync the FreeRDP fork and make PRs to the FreeRDP master repo, like this one: https://blog.falafel.com/how-to-update-a-github-forked-repository/ (the website SSL certificate recently expired but you can proceed to the page). I use both SourceTree and TortoiseGit_

3) Login page, sometimes mrytille sometimes enterprise, when the page loads
it checks that the enterprise services/mfa are enabled before displaying
input boxes, if the myrtille.services is not running when the page is
loaded it will display the normal login page, shall I change to hide the
login page if the services are not running?

_The logic is good, don't change anything :) I think the issue can only happen only under Visual Studio because the web application can be started and a browser opened before the myrtille WCF services are up and running._

4) Password on login, the whole point behind the enterprise mode is that
there is preauthentication against a domain to verify what servers the user
is allowed to access, therefore if enterprise mode is enabled the password
must be the domain password.

_Yes, I understand :) but I was thinking about the end user, who may not be a developer. A tooltip on the text field would be good and, mostly, a new section into the myrtille documentation providing a minimal guidance regarding the configuration (https://github.com/bigpjo/myrtille/blob/master/Myrtille.Services/app.config#L134)_

5) MFA, the user must be enroled for MFA, the OASIS platform has a
directory sync service which will sync and send registration emails for all
users they wish to have MFA. If Myrtille is not used in enterprise mode,
the owner will have to register the user in the OASIS administration
platform to register for MFA, in both cases the user will have instructions
to download google authenticator.

_Same here ;) a little information and link to the OASIS platform into the documentation would be nice. Otherwise, users who are not used to 2FA will be lost._

6) The server delete, I totally understand, I can change the link to have
the word "edit" when an administrator is viewing to make it more intuitive.
I can also add a delete icon/button if you think that would be better!

_Yes :)_

7) Session disconnect redirect to login. I appreciate this could be found
as being frustrating, when a user preauthenticates the enterprise adapter
stores the user credentials and a session key encrypted in the database,
this is valid for no more than 1 hour, when a user connects to a server the
credentials are read from the database based on session key and then
deleted, this is to ensure that whist the user is using the service no
credentials are stored client side (at all!) and server side in any form
that can be used by someone who should not have access. Because of this,
upon disconnect the session no longer exists and the user needs to login
again. I have done some Q&A sessions in the 2 companies I have now
implemented Myrtille and in both cases this is the preferred option.

_Yes, it's good; but the inability to click anything beside the logout button after an host disconnect is a little confusing. In this case, perhaps better logout automatically and redirect directly to the login page._

I think all in all enterprise mode may not be required by Myrtille users,
however I see the potential of Myrtille and its uses, as you are aware from
our previous discussions what is required in an enterprise environment may
not be the same as users who wish to access there home network. I tried to
abstract Myrtille from the enterprise functions to give the users the
choice.

_Yes, all good. By default, the 2FA and enterprise mode will be disabled but with the end user will have the option to enable them (from [configuration](https://github.com/bigpjo/myrtille/blob/master/Myrtille.Services/app.config#L134)). I didn't tested (I certainly will), do you confirm it's possible to enable only enterprise mode or 2FA (not both of them)?_

With regards MFA and OASIS, yes it is a little complicated and feedback to
streamline the process is welcome, the issue is that to enable 2fa you need
to store keys for generation of the TOTP codes, it can be changed to
provide a services much the same as enterprise mode i.e. create databases,
handle enrollment of users etc but I dont think the whole process will be
much simpler than integration with OASIS. Again as with previous
discussions, OASIS is optional, it can be removed if the community and
yourself do not want it in there.

_No, better keep the users creation and enrollment process on your platform. About OASIS, as discussed, it's fair enough to have it optional and up to 10 users free, so it's welcome :) if someone wants to use another MFA provider, up to him to tweak the code and change the configuration.

I look forward to hearing back from you.

Regards

Paul

**Comment by bigpjo** [comment]
Thanks Cedric,

I will sort all of these over the weekend and I will make a new pull
request Sunday if thats ok.

Regards

Paul

**Comment by cedrozor** [comment]
Thanks Paul, it would be perfect :)

**Comment by bigpjo** [comment]
I resynced the fork. Sorted conflicts and am retesting.

I think most of the other issues you reported were caused because the PR
must not have all the changes etc I have done since the original PR.

I am in the process of updating the documentation with instructions etc.
Should have that finished tomorrow.

**Comment by cedrozor** [comment]
> I think most of the other issues you reported were caused because the PR
> must not have all the changes etc I have done since the original PR.

I don't think because I tested from your fork directly.

> Should have that finished tomorrow.

Nice :)

**Comment by bigpjo** [comment]
Hmmmm how odd. Ok. I will check check and recheck

**Comment by bigpjo** [comment]
Will create a new pull request for changes

**Pull request closed without merging**
