### PR TITLE
Master

### PR DESCRIPTION
**Pull request by bigpjo**
SSH support
Enterprise mode prompt for user credentials
Enterprise mode start program configuration

### CODE REVIEW

**Comment by cedrozor** [comment]
Hi Paul, thanks for the new PR! you don't do things by half, as always :) It looks good! I'm going to check and, hopefully, don't refactor anything ;)

**Comment by bigpjo** [comment]
Hi Cedric There is an update to oasis.integration on nuget. I can make a new pull request to include this package unless you are happy to update before next build

**Comment by cedrozor** [comment]
Hi Paul, no problem for a new PR; I'm working from your fork anyway and it will allow you to include the 1.9.1 (small release). Thanks :)

**Comment by bigpjo** [comment]
Thanks cedrix

**Comment by bigpjo** [comment]
Closed due to merge after 1.9.1 changes

**Pull request closed without merging**
