### PR TITLE
Enterprise mode and 2fa

### PR DESCRIPTION
**Pull request by bigpjo**
Enterprise mode and two-factor authentication

### CODE REVIEW

**Comment by cedrozor** [comment]
Hi Paul, thanks for the new PR! :) I will make some tests tomorrow before merging.

I'm a bit worried about regressions... for example, there is still the mouse right click toggle missing from **default.aspx** and you refactored the session fixation protection code (generating a new http session ID) into **default.aspx.cs** (perhaps you improved it, I'll check that). Into **myrtille.js**, you completely disabled the redirection code which, in addition to the session fixation protection, is also used for the auto-connect / start program from url feature (do they still work?).

Regarding the versioned files, the **.vs/config** folder shouldn't be commited (it's your local VS config), neither **packages** (the nuget packages are automatically downloaded if missing from your local environment; the only thing needed are the _packages.config_ files into the different projects). Same for **.gitignore**, it shouln't be commited. **Dlls and exe** into the root folder aren't super clean either.

Sorry for being picky, these are details! ;) I can make some cleaning after merging anyway.

About the SQLCE dependencies, including the redistributables is ok but you also have another solution which is to define SQLCE as [prerequisite into the installer bootstrap](https://stackoverflow.com/questions/8078150/setup-project-sql-compact-4-prerequisites). Having 2 installers is fine but it implies more maintenance... a bootstrap prerequisite could download the right dlls depending on the OS. But it's a detail if the installers (x86 and x64) are working (do they? I need to check that also).

Thanks for the documentation! :) it's the annoying thing to do, but so important! and it's always rewarding to push forward something you do.

**Comment by bigpjo** [comment]
Hi Cedric

I have double checked the default.aspx page, the right-click toggle is on
line 146, I had issues with the merge so some parts had to be manually
corrected, so maybe it is not quite the same as you originally wrote it.
Sorry for that.

With regards the myrtille.js file, I completed a number of tests with IIS
as reverse proxy, haproxy and nginx, the issue with the session ID in the
URL is it is created by the webserver, the connections being managed by the
proxy does not understand them and therefore cannot display pages. By
removing the redirect and creating new sessions server side when the page
reloads seemed a good method to resolve the issue, but as you have more
experience with this your comments are welcome.

With regards the autoconnect/start program from url, this should behave
exactly the same if enterprise mode is disabled, as per the documentation,
if enterprise mode is enabled the sessions can be created by the users with
administration access, this creates a unique session URL, this URL is
verified by the enterprise service and connects to the correct host using
specified username and password etc without having to first hash the
password etc.

Your comment about the .vs and dlls exes included in the PR, I have an
issue with gitwin, I have my own repository for projects such as this and a
company one, each time I switch between the two I loose the ignore
settings, its very frustrating, shall I remove these folders and create a
new PR?

Your not being pickey, you have a very tidy project where you have put a
lot of effort in so it has to be right, I dont want to break anything!!

Could you please elaborate on the DLL/exe in root folder issue?

As for the bootstrap installer for SQLCE, installers are not really my
thing, I normally use a contractor to create them for me, there is a cost
to me which I do not mind paying, I created the second installer as I edged
my bets that most will use 64bit installer and the 32bit version was just
to cover all bases, but if this is not acceptable, helping to create a
single installer would be much appreciated.

Please could you confirm what I need to do to finish this off

Thanks and have a nice evening

Paul





On 17 Feb 2018 18:51, "cedrozor" <notifications@github.com> wrote:

Hi Paul, thanks for the new PR! :) I will make some tests tomorrow before
merging.

I'm a bit worried about regressions... for example, there is still the
mouse right click toggle missing from *default.aspx* and you refactored the
session fixation protection code (generating a new http session ID) into
*default.aspx.cs* (perhaps you improved it, I'll check that). Into
*myrtille.js*, you completely disabled the redirection code which, in
addition to the session fixation protection, is also used for the
auto-connect / start program from url feature (do they still work?).

Regarding the versioned files, the *.vs/config* folder shouldn't be
commited (it's your local VS config), neither *packages* (the nuget
packages are automatically downloaded if missing from your local
environment; the only thing needed are the *packages.config* files into the
different projects). Same for *.gitignore*, it shouln't be commited. *Dlls
and exe* into the root folder aren't super clean either.

Sorry for being picky, these are details! ;) I can make some cleaning after
merging anyway.

About the SQLCE dependencies, including the redistributables is ok but you
also have another solution which is to define SQLCE as prerequisite into
the installer bootstrap
<https://stackoverflow.com/questions/8078150/setup-project-sql-compact-4-prerequisites>.
Having 2 installers is fine but it implies more maintenance... a bootstrap
prerequisite could download the right dlls depending on the OS. But it's a
detail if the installers (x86 and x64) are working (do they? I need to
check that also).

Thanks for the documentation! :) it's the annoying thing to do, but so
important! and it's always rewarding to push forward something you do.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cedrozor/myrtille/pull/90#issuecomment-366462945>, or mute
the thread

**Comment by cedrozor** [comment]
> Hi Cedric
> 
> I have double checked the default.aspx page, the right-click toggle is on
> line 146, I had issues with the merge so some parts had to be manually
> corrected, so maybe it is not quite the same as you originally wrote it.
> Sorry for that.
> 

The file was probably in conflict so you had to merge manually, and forgot the line.

> With regards the myrtille.js file, I completed a number of tests with IIS
> as reverse proxy, haproxy and nginx, the issue with the session ID in the
> URL is it is created by the webserver, the connections being managed by the
> proxy does not understand them and therefore cannot display pages. By
> removing the redirect and creating new sessions server side when the page
> reloads seemed a good method to resolve the issue, but as you have more
> experience with this your comments are welcome.

Seems good, I will check that.

> With regards the autoconnect/start program from url, this should behave
> exactly the same if enterprise mode is disabled, as per the documentation,
> if enterprise mode is enabled the sessions can be created by the users with
> administration access, this creates a unique session URL, this URL is
> verified by the enterprise service and connects to the correct host using
> specified username and password etc without having to first hash the
> password etc.

Nice, this could be added to the documentation.

> Your comment about the .vs and dlls exes included in the PR, I have an
> issue with gitwin, I have my own repository for projects such as this and a
> company one, each time I switch between the two I loose the ignore
> settings, its very frustrating, shall I remove these folders and create a
> new PR?

No, it was just for info. I can remove them after merge.

> Your not being pickey, you have a very tidy project where you have put a
> lot of effort in so it has to be right, I dont want to break anything!!
> 
> Could you please elaborate on the DLL/exe in root folder issue?

CertEnroll.dll, CertEnroll_Interop.dll and TlbImp.exe

> As for the bootstrap installer for SQLCE, installers are not really my
> thing, I normally use a contractor to create them for me, there is a cost
> to me which I do not mind paying, I created the second installer as I edged
> my bets that most will use 64bit installer and the 32bit version was just
> to cover all bases, but if this is not acceptable, helping to create a
> single installer would be much appreciated.
> 
> Please could you confirm what I need to do to finish this off

I was thinking after this. In fact, wfreerdp is built in 32 bits (because of openssl, the 1.0.x version was 32 bits), so myrtille is packaged with an x86 installer. Thus, there is no need for the 64 bits SQLCE; 1 setup only is good enough (wfreerdp memory footprint is low and there is no need for 4+ GB of RAM).

Thanks and have a nice evening

Paul

**Comment by cedrozor** [comment]
Hi Paul,

So I made some tests/debug this afternoon and it was a bit frustrating :/

I had first to replace IIS Express by the standard IIS. By the way, the folder **.vs/config** you have commited is the IIS Express configuration for your local dev environment.

Then I tried to authenticate the OTP with myrtille, I had an SSL/TLS exception because my machine clock wasn't up to date; it's normal, just to mention (and after resyncing the clock, it was ok)... but the error message could me more explicit (you can check the inner exception). Also, some OTPs are only valid for a few seconds, maybe you can extend the minimum duration to 30 secs or so.

Once logged in, the hosts list appears. You added an "edit" prefix before them, that's good.

Then I had very weird issues :/ it started after I tried to connect an host. The connection failed and it was not due to myrtille but to the connection broker. It was probably bugged because the same connection using mstsc also failed and it worked again after I restarted the connection broker machine.

But myrtille didn't liked that because any subsequent connection (same host or another) also failed. It wasn't due to the connection broker this time but to the communication pipes (used between the myrtille web application and wfreerdp) being broken. I checked the applications and system event logs and they reported many warnings and errors with the myrtille application pool and ASP.NET.

I suspect it's related to breakpoints into the various asynchronous webmethod because, when I removed them, all went good (?!). Did you experienced such things? The original myrtille don't use async webmethods but classic postback events. I wonder if it's related, but it's fatal to myrtille.

Once connected to an host, all works good except 1 (major) thing: reloading the page (F5) gets you back to the login page. This breaks many myrtille features, such as scale display, debug, stats modes and fallback to long-polling (HTML4) if the browser doesn't support websockets, or if there is a communication issue using them.

I understand the security aspects of not using an http session id into the url, but it also break the collaborative mode (quite basic, I agree) proposed by myrtille (by sharing the myrtille url, including the http session id, with someone); if the page uses https, the http session id is secure.

The http session id is also required for xhr calls; even when using websockets (persistent connection), there is a keep alive polling, using xhr, to maintain the http session active.

Last but not least, if someone wants to tweak the **config.js** file, he can't reload the page without being disconnected.

Regarding the original myrtille mode (disabling both MFA and enterprise modes), it works but same remark as above. Also, if they are disabled, there is no need to run the related WCF services (to avoid any confusion).

And why disabling the remote clipboard button?

Cedric

**Comment by cedrozor** [comment]
After checking a bit more the web config file, you use a standard (cookie mode) http session (it couldn't had worked anyway, without an http context). So you just removed the `cookieless="UseUri"` option.

You also broke the myrtille incognito/private mode :/ * sigh *

**Comment by bigpjo** [comment]
Hi Cedric


Then I tried to authenticate the OTP with myrtille, I had an SSL/TLS
exception because my machine clock wasn't up to date; it's normal, just to
mention (and after resyncing the clock, it was ok)... but the error message
could me more explicit (you can check the inner exception). Also, some OTPs
are only valid for a few seconds, maybe you can extend the minimum duration
to 30 secs or so.

 - *The API requests to OASIS allow for a certain time difference between
machine making call and our platform, this is a security measure to prevent
replay of API calls, this can be extended and I will double check, it was 5
minutes but we may have reduced this in our last release. With regards the
OTP codes only being valid for a few seconds, the TOTP generation is based
on intervals of time which is default 30 seconds, this is not from when you
request the code it is from a fixed point, so there will be instances where
the code could only be valid for 5 seconds, however, to get around this,
our platform will accept a code 1 step back and 1 step forward so time
differences on mobiles etc will have less of an impact, the most important
thing though is that the RFC and best practice for 2fa with TOTP is that a
code can only be used once! This may be what was causing an issue.*

Then I had very weird issues :/ it started after I tried to connect an
host. The connection failed and it was not due to myrtille but to the
connection broker. It was probably bugged because the same connection using
mstsc also failed and it worked again after I restarted the connection
broker machine.

But myrtille didn't liked that because any subsequent connection (same host
or another) also failed. It wasn't due to the connection broker this time
but to the communication pipes (used between the myrtille web application
and wfreerdp) being broken. I checked the applications and system event
logs and they reported many warnings and errors with the myrtille
application pool and ASP.NET <http://asp.net/>.

I suspect it's related to breakpoints into the various asynchronous
webmethod because, when I removed them, all went good (?!). Did you
experienced such things? The original myrtille don't use async webmethods
but classic postback events. I wonder if it's related, but it's fatal to
myrtille.

- We had an issue when running Myrtille with the webmethods and enterprise
mode, it really did not play well on windows servers where the service was
running from the BIN folder of the website! I dont know why, 3 of us looked
at it and the only way we could get it to work was if we moved the services
outside the website BIN folder, hence the installer changes.

Once connected to an host, all works good except 1 (major) thing: reloading
the page (F5) gets you back to the login page. This breaks many myrtille
features, such as scale display, debug, stats modes and fallback to
long-polling (HTML4) if the browser doesn't support websockets, or if there
is a communication issue using them.

- This is a problem I see now and would mean a rewrite, when writing
enterprise mode we looked at a number of ways of doing it, mainly because
of the single page approach to the login, working within Myrtille.

I understand the security aspects of not using an http session id into the
url, but it also break the collaborative mode (quite basic, I agree)
proposed by myrtille (by sharing the myrtille url, including the http
session id, with someone); if the page uses https, the http session id is
secure.

- I understand what you are saying here, I do have a question, the whole
point behind the session fixation attack changes were to prevent someone
reusing a session, wouldnt this approach allow someone very easily to
hijack a session, admittedly the collaborative changes were done after I
made the changes for enterprise mode so this was not considered.

Last but not least, if someone wants to tweak the *config.js* file, he
can't reload the page without being disconnected.

- Yes I can see that would be a problem.

Regarding the original myrtille mode (disabling both MFA and enterprise
modes), it works but same remark as above. Also, if they are disabled,
there is no need to run the related WCF services (to avoid any confusion).

- I agree, the reason the services are still run is so that Myrtille can
check with the service to see if they have been enabled, I thought it would
be nicer than having another config setting somewhere and just handle it
all as a part of the service!

And why disabling the remote clipboard button?

- There is a config setting to disable this, new GDPR rules mean that if a
company was to use this they have to be confident in the security of
customer data, there are more than one option to get data offsite,
restricting access to the clipboard was a request.

You also broke the myrtille incognito/private mode

- This works fine.


I think here we have a little bit of a situation, should I just remove
enterprise mode and manage it as a separate project? I really wanted to
share the work I had done with the community as it is now installed with
two of our customers, one with 50 users the other has finished testing and
will be rolling out to 500 remote users, none have had any issues.

It is not a problem not maintaining this as a part of the main project.


Thanks


Paul

**Comment by cedrozor** [comment]
Hi Paul,

> We had an issue when running Myrtille with the webmethods and enterprise
> mode, it really did not play well on windows servers where the service was
> running from the BIN folder of the website! I dont know why, 3 of us looked
> at it and the only way we could get it to work was if we moved the services
> outside the website BIN folder, hence the installer changes.
> 

Which issue was it?

> This is a problem I see now and would mean a rewrite, when writing
> enterprise mode we looked at a number of ways of doing it, mainly because
> of the single page approach to the login, working within Myrtille.
> 

It's only a technical issue; it must possible to reload the page without being disconnected (I'll check it).

> I understand what you are saying here, I do have a question, the whole
> point behind the session fixation attack changes were to prevent someone
> reusing a session, wouldnt this approach allow someone very easily to
> hijack a session, admittedly the collaborative changes were done after I
> made the changes for enterprise mode so this was not considered.
> 

Yes, it's to avoid a link with a session id already in it; someone log in with it and the attacker can just use the url and he can see / control the remote session.
Indeed, when sharing your remote session url with someone, for a collaborative work, you have to be very cautious.

> Last but not least, if someone wants to tweak the *config.js* file, he
> can't reload the page without being disconnected.
> 
> Yes I can see that would be a problem.
> 

People don't do that very often, I agree; but it feels weird to just reload the page and be disconnected.

> I agree, the reason the services are still run is so that Myrtille can
> check with the service to see if they have been enabled, I thought it would
> be nicer than having another config setting somewhere and just handle it
> all as a part of the service!

Yes, it makes sense.

> And why disabling the remote clipboard button?
> 
> There is a config setting to disable this, new GDPR rules mean that if a
> company was to use this they have to be confident in the security of
> customer data, there are more than one option to get data offsite,
> restricting access to the clipboard was a request.
> 

I agree.

> You also broke the myrtille incognito/private mode
> 
> This works fine.

If cookies are disabled, there is no way to store the http session id into a cookie... that's why it must be passed into the url.

> I think here we have a little bit of a situation, should I just remove
> enterprise mode and manage it as a separate project? I really wanted to
> share the work I had done with the community as it is now installed with
> two of our customers, one with 50 users the other has finished testing and
> will be rolling out to 500 remote users, none have had any issues.
> 
> It is not a problem not maintaining this as a part of the main project.

Nah, we worked on this and we'll finish it ;) when does a @&! software will bother us?

Thanks,
Cedric

**Comment by cedrozor** [comment]
Hi Paul, I'm on it ;)

**Comment by cedrozor** [comment]
No don't worry, you made enough. I'm integrating MFA and enterprise into myrtille with minimal refactoring

**Comment by bigpjo** [comment]
Are you sure? I feel like I didn't do they best job.

**Comment by cedrozor** [comment]
Yes sure, no problem; I needed to refactor a bit that redirect stuff on the default page anyway

**Comment by bigpjo** [comment]
Ok. If I can do anything let me know.

**Comment by cedrozor** [comment]
Hi Paul,

I finally managed to implement both features into the myrtille master branch! :) thanks again for the pull request but, as discussed, I really had to refactor for a better knowledge and integration with the rest.

I just changed one thing on the backend side: if the enterprise session isn't one time when getting an host connection details, it isn't logged out (https://github.com/cedrozor/myrtille/blob/master/Myrtille.Enterprise/ActiveDirectory.cs#L460).

Changes are mainly on the frontend, replacing ajax webmethods by simple postbacks and taking advantage of .NET stuff (repeaters binding, etc) instead of js code. Many things could be improved (for example using MVC patterns, REST services, etc) but lets keep it simple ;)

I also tweaked a bit (but very little) the documentation you had wrote.

I hope it will fit your needs, so we can work from this version in future releases! :)

Cedric

**Comment by bigpjo** [comment]
Hi Cedric

A big thank you for the effort you put in to enable these features to be
included.

I have a list of requirements that I will start now and will adhere
strongly to the style of the project (to save reforactoring ;))

As I mentioned before it is a fantastic project and the work that has been
put into it shows.

Best regards

Paul

**Pull request closed without merging**
